heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server, configured to be a
  web node in a Magento CE configuration.

parameters:

  hostname:
    description: Web Server Hostname
    type: string
    default: Magento-Web
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    description: Server Image used for all servers.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    description: Web Cloud Server flavor
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  domain:
    description: Domain to be used with Magento site
    type: string
    default: "example.com"

  # Magento Settings
  php_fpm_master:
    description: "IP of the Master node"
    type: string

  # SSH Keypair naming
  ssh_keypair_name:
    description: "keypair name to register with Nova for the root SSH key"
    type: string

  ssh_private_key:
    type: string

  lsync_pub:
    description: Public key for lsync configuration
    type: string

  # Chef configuration options
  kitchen:
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/magento-multi

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.14.2

  # parent stack id for metadata
  parent_stack_id:
    description: Stack id of the parent stack
    type: string
    default: "none"

resources:
  web_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      metadata:
        rax-heat: { get_param: parent_stack_id }

  web_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: wp_web_server
    properties:
      username: root
      private_key: { get_param: ssh_private_key }
      host: { get_attr: [web_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        rax:
          lsyncd:
            ssh:
              pub: { get_param: lsync_pub }
        run_list: ["recipe[apt]",
                   "recipe[build-essential]",
                   "recipe[rax-magento::web]"]

outputs:
  accessIPv4:
    value: { get_attr: [web_server, accessIPv4] }

  privateIPv4:
    value: { get_attr: [web_server, privateIPv4] }
